Add sqv support
This uses the verification-only command from Sequoia-PGP which is going
to be present on new Debian installations that have apt installed, as
apt has switched to it from gpgv to sqv since 2.9.19.

Closes: #1091588

diff --git a/debootstrap b/debootstrap
--- a/debootstrap
+++ b/debootstrap
@@ -383,8 +383,8 @@ if [ $# != 0 ] ; then
 		shift
 		;;
 	    --keyring|--keyring=?*)
-		if ! in_path sopv && ! in_path gpgv; then
-			error 1 NEEDPGPV "neither of sopv or gpgv are installed, but required for Release verification"
+		if ! in_path sopv && ! in_path sqv && ! in_path gpgv; then
+			error 1 NEEDPGPV "none of sopv, sqv or gpgv are installed, but required for Release verification"
 		fi
 		if [ "$1" = "--keyring" ] && [ -n "$2" ]; then
 			KEYRING="$2"
diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -688,6 +688,10 @@ download_release_sig () {
 			local rc=0
 			sopv verify "$relsigdest" "$KEYRING" <"$reldest" || rc=$?
 			check_sop_status "$rc"
+		elif in_path sqv; then
+			local rc=0
+			sqv --keyring "$KEYRING" "$relsigdest" "$reldest" || rc=$?
+			check_sqv_status "$rc"
 		else
 			# Don't worry about the exit status from gpgv; parsing the output will
 			# take care of that.
@@ -1907,6 +1911,21 @@ check_sop_status () {
 		;;
 	    *)
 		error 1 SIGCHECK "Error executing sopv to check Release signature (SOP error $err)"
+		;;
+	esac
+}
+
+check_sqv_status () {
+	local err="$1"
+	case "$err" in
+	    0)
+		info VALIDRELSIG "Valid Release signature"
+		;;
+	    1)
+		error 1 BADRELSIG "Invalid Release signature"
+		;;
+	    *)
+		error 1 SIGCHECK "Error executing sqv to check Release signature (sqv error $err)"
 		;;
 	esac
 }
