Fix several shellcheck complaints
Fix several shellcheck complaints except for those where word splitting
is desired:

```
shellcheck -e SC1090,SC1091,SC2034,SC2046,SC2086,SC2089,SC2090,SC2119,SC2153,SC2209,SC3043 \
    -s sh -x debootstrap functions scripts/gutsy scripts/kali scripts/sid
```

Signed-off-by: Benjamin Drung <bdrung@ubuntu.com>

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -33,6 +33,7 @@ error () {
 		for x in "$@"; do echo "EA: $x"; done
 		echo "EF: $fmt") >&4
 	else
+		# shellcheck disable=SC2059
 		(printf "E: $fmt\n" "$@") >&4
 	fi
 	exit "$err"
@@ -49,6 +50,7 @@ warning () {
 		for x in "$@"; do echo "WA: $x"; done
 		echo "WF: $fmt") >&4
 	else
+		# shellcheck disable=SC2059
 		printf "W: $fmt\n" "$@" >&4
 	fi
 }
@@ -64,6 +66,7 @@ info () {
 		for x in "$@"; do echo "IA: $x"; done
 		echo "IF: $fmt") >&4
 	else
+		# shellcheck disable=SC2059
 		printf "I: $fmt\n" "$@" >&4
 	fi
 }
@@ -71,7 +74,6 @@ info () {
 PROGRESS_NOW=0
 PROGRESS_END=0
 PROGRESS_NEXT=""
-PROGRESS_WHAT=""
 
 progress_next () {
 	PROGRESS_NEXT="$1"
@@ -91,8 +93,8 @@ wgetprogress () {
 		# non-zero exit status would cause the echo command to be
 		# skipped.  If wget succeeds, $ret will be "", so it then has to
 		# be set to a default value of 0.
-		ret=$({ { wget $@ 2>&1 >/dev/null || echo $? >&2; } | "$PKGDETAILS" "WGET%" "$PROGRESS_NOW" "$PROGRESS_NEXT" "$PROGRESS_END" >&3; } 2>&1)
-		: ${ret:=0}
+		ret=$({ { wget "$@" 2>&1 >/dev/null || echo $? >&2; } | "$PKGDETAILS" "WGET%" "$PROGRESS_NOW" "$PROGRESS_NEXT" "$PROGRESS_END" >&3; } 2>&1)
+		: "${ret:=0}"
 	else
 		wget ${NVSWITCH:+"$NVSWITCH"} "$@"
 		ret=$?
@@ -139,7 +141,7 @@ dpkg_progress () {
 	}
 
 	exitcode=0
-	while read status pkg qstate; do
+	while read -r status pkg qstate; do
 		if [ "$status" = "EXITCODE" ]; then
 			exitcode="$pkg"
 			continue
@@ -261,7 +263,7 @@ SUPPORTED_VARIANTS="-"
 variants () {
 	local v
 	SUPPORTED_VARIANTS="$*"
-	for v in $*; do
+	for v in "$@"; do
 		if doing_variant "$v"; then return 0; fi
 	done
 	error 1 UNSUPPVARIANT "unsupported variant"
@@ -269,8 +271,8 @@ variants () {
 
 ########################################################### option handling
 check_conflicting_option () {
-	if ( [ "$set_what_to_do" = --foreign ] && [ "${1%%=*}" = --unpack-tarball ] ) || \
-	   ( [ "${set_what_to_do%%=*}" = "--unpack-tarball" ] && [ "$1" = --foreign ] ); then
+	if { [ "$set_what_to_do" = --foreign ] && [ "${1%%=*}" = --unpack-tarball ]; } || \
+	   { [ "${set_what_to_do%%=*}" = "--unpack-tarball" ] && [ "$1" = --foreign ]; }; then
 		LOOSEN_CONFLICTING_RESTRICTION="true"
 	elif [ -n "$set_what_to_do" ]; then
 		error 1 ARG_CONFLICTING "$set_what_to_do is specified with $1, please use only one of those options."
@@ -317,9 +319,9 @@ verify_checksum () {
 		fi
 	else
 		if in_path "sha${SHA_SIZE}sum"; then
-			relchecksum="$(sha${SHA_SIZE}sum < "$1" | sed 's/ .*$//')"
+			relchecksum="$("sha${SHA_SIZE}sum" < "$1" | sed 's/ .*$//')"
 		elif in_path "sha${SHA_SIZE}"; then
-			relchecksum="$(sha${SHA_SIZE} < "$1")"
+			relchecksum="$("sha${SHA_SIZE}" < "$1")"
 		else
 			error 1 SIGCHECK "Cannot check sha${SHA_SIZE}sum"
 		fi
@@ -374,16 +376,17 @@ get () {
 	if [ "$#" -gt 3 ]; then
 		local st=1
 		if [ "$3" = "-" ]; then st=4; fi
-		local order="$(a=$st; while [ "$a" -le $# ]; do eval echo \"\${$(($a+1))}\" $a;
-		a=$(($a + 3)); done | sort -n | sed 's/.* //')"
+		local order
+		order="$(a=$st; while [ "$a" -le $# ]; do eval "echo \"\${$((a+1))}\" $a";
+			a=$((a + 3)); done | sort -n | sed 's/.* //')"
 	else
 		local order=1
 	fi
 	for a in $order; do
 		local checksum siz typ from dest iters
-		checksum="$(eval echo \${$a-})"
-		siz="$(eval echo \${$(( $a+1 ))-})"
-		typ="$(eval echo \${$(( $a+2 ))-})"
+		checksum="$(eval "echo \${$a-}")"
+		siz="$(eval "echo \${$(( a+1 ))-}")"
+		typ="$(eval "echo \${$(( a+2 ))-}")"
 		iters="0"
 
 		case "$typ" in
@@ -393,7 +396,7 @@ get () {
 		    *)   from="$from_base"; dest="$dest_base" ;;
 		esac
 
-		if [ ! -z "$CACHE_DIR" ]; then
+		if [ -n "$CACHE_DIR" ]; then
 			dest="${dest%%*/}"
 		elif [ "${dest#/}" = "$dest" ]; then
 			dest="./$dest"
@@ -432,7 +435,7 @@ get () {
 			else
 				rm -f "$dest2"
 				warning RETRYING "Retrying failed download of %s" "$from"
-				iters=$(($iters + 1))
+				iters=$((iters + 1))
 			fi
 		done
 		warning CORRUPTFILE "%s was corrupt" "$from"
@@ -467,7 +470,8 @@ just_get () {
 			return 1
 		fi
 	elif [ "${from#ssh:}" != "$from" ]; then
-		local ssh_dest="$(echo "$from" | sed -e 's#ssh://##' -e 's#/#:/#')"
+		local ssh_dest
+		ssh_dest="$(echo "$from" | sed -e 's#ssh://##' -e 's#/#:/#')"
 		if [ -n "$ssh_dest" ]; then
 			scp "$ssh_dest" "$dest"
 			return 0
@@ -490,7 +494,7 @@ download_indices () {
 }
 
 debfor () {
-	(while read pkg path; do
+	(while read -r pkg path; do
 		for p in "$@"; do
 			[ "$p" = "$pkg" ] || continue;
 			echo "$path"
@@ -533,7 +537,7 @@ get_release_checksum () {
 		local match="^[Ss][Hh][Aa]$SHA_SIZE:"
 	fi
 	sed -n "/$match/,/^[^ ]/p" < "$reldest" | \
-		while read a b c; do
+		while read -r a b c; do
 			if [ "$c" = "$path" ]; then echo "$a $b"; fi
 		done | head -n 1
 }
@@ -617,17 +621,17 @@ split_inline_sig () {
 	while IFS= read -r line; do
 		case "${state}" in
 		    pre-begin)
-			if [ "x${line}" = "x-----BEGIN PGP SIGNED MESSAGE-----" ]; then
+			if [ "${line}" = "-----BEGIN PGP SIGNED MESSAGE-----" ]; then
 				state="begin"
 			fi
 			;;
 		    begin)
-			if [ "x${line}" = "x" ]; then
+			if [ "${line}" = "" ]; then
 				state="data"
 			fi
 			;;
 		    data)
-			if [ "x${line}" = "x-----BEGIN PGP SIGNATURE-----" ]; then
+			if [ "${line}" = "-----BEGIN PGP SIGNATURE-----" ]; then
 				printf "%s\n" "${line}" > "$relsigdest"
 				state="signature"
 			else
@@ -637,7 +641,7 @@ split_inline_sig () {
 			;;
 		    signature)
 			printf "%s\n" "${line}" >> "$relsigdest"
-			if [ "x${line}" = "x-----END PGP SIGNATURE-----" ]; then
+			if [ "${line}" = "-----END PGP SIGNATURE-----" ]; then
 				break
 			fi
 		esac
@@ -730,7 +734,7 @@ download_release_indices () {
 					i="$gzi"
 				fi
 				if [ "$i" != "" ]; then
-					totalpkgs=$(( $totalpkgs + ${i#* } ))
+					totalpkgs=$(( totalpkgs + ${i#* } ))
 				else
 					mv "$reldest" "$reldest.malformed"
 					error 1 MISSINGRELENTRY "Invalid Release file, no entry for %s" "$subpath"
@@ -766,7 +770,7 @@ download_release_indices () {
 					ext="$ext $gzi gz"
 					i="${i:-$gzi}"
 				fi
-				progress_next $(($donepkgs + ${i#* }))
+				progress_next $((donepkgs + ${i#* }))
 				for m in $MIRRORS; do
 					pkgdest="$TARGET/$($DLDEST pkg "$s" "$c" "$a" "$m" "$path")"
 					if get "$m/$path" "$pkgdest" $ext; then break; fi
@@ -774,7 +778,7 @@ download_release_indices () {
 				if [ ! -f "$pkgdest" ]; then
 					error 1 COULDNTDL "Couldn't download %s" "$m/$path"
 				fi
-				donepkgs=$(($donepkgs + ${i#* }))
+				donepkgs=$((donepkgs + ${i#* }))
 				progress $donepkgs $totalpkgs DOWNPKGS "Downloading Packages files"
 			done
 		done
@@ -790,13 +794,13 @@ get_package_sizes () {
 		newleft=""
 		totaldebs=0
 		countdebs=0
-		while read p details; do
+		while read -r p details; do
 			if [ "$details" = "-" ]; then
 				newleft="$newleft $p"
 			else
 				size="${details##* }";
-				totaldebs=$(($totaldebs + $size))
-				countdebs=$(($countdebs + 1))
+				totaldebs=$((totaldebs + size))
+				countdebs=$((countdebs + 1))
 			fi
 		done
 		echo "$countdebs $totaldebs$newleft"
@@ -812,19 +816,19 @@ download_debs () {
 
 	"$PKGDETAILS" PKGS "$m" "$pkgdest" "$@" | (
 		leftover=""
-		while read p ver arc mdup fil checksum size; do
+		while read -r p ver arc mdup fil checksum size; do
 			if [ "$ver" = "-" ]; then
 				leftover="$leftover $p"
 			else
-				progress_next $(($dloaddebs + $size))
+				progress_next $((dloaddebs + size))
 				debdest="$($DLDEST deb "$p" "$ver" "$arc" "$m" "$fil")"
 				debcache="$(echo "$p"_"$ver"_"$arc".deb | sed 's/:/%3a/')"
 				if [ -z "$CACHE_DIR" ] && get "$m/$fil" "$TARGET/$debdest" "$checksum" "$size"; then
-					dloaddebs=$(($dloaddebs + $size))
+					dloaddebs=$((dloaddebs + size))
 					echo >>"$TARGET/debootstrap/deburis" "$p $ver $m/$fil"
 					echo >>"$TARGET/debootstrap/debpaths" "$p $debdest"
 				elif [ -d "$CACHE_DIR" ] && get "$m/$fil" "$CACHE_DIR/$debcache" "$checksum" "$size"; then
-					dloaddebs=$(($dloaddebs + $size))
+					dloaddebs=$((dloaddebs + size))
 					echo >>"$TARGET/debootstrap/deburis" "$p $ver $m/$fil"
 					echo >>"$TARGET/debootstrap/debpaths" "$p $debdest"
 					cp "$CACHE_DIR/$debcache" "$TARGET/$debdest"
@@ -852,8 +856,8 @@ download_release () {
 	leftoverdebs="$*"
 
 	# Fix possible duplicate package names, which would screw up counts:
-	leftoverdebs=$(printf "$leftoverdebs"|tr ' ' '\n'|sort -u|tr '\n' ' ')
-	numdebs=$(printf "$leftoverdebs"|wc -w)
+	leftoverdebs=$(printf "%s" "$leftoverdebs"|tr ' ' '\n'|sort -u|tr '\n' ' ')
+	numdebs=$(printf "%s" "$leftoverdebs"|wc -w)
 
 	archs="$ARCH"
 	if [ $ARCH_ALL_SUPPORTED -eq 1 ]; then
@@ -873,7 +877,7 @@ download_release () {
 
 				leftoverdebs="$(get_package_sizes "$m1" "$pkgdest" $leftoverdebs)"
 
-				countdebs=$(($countdebs + ${leftoverdebs%% *}))
+				countdebs=$((countdebs + ${leftoverdebs%% *}))
 				leftoverdebs=${leftoverdebs#* }
 
 				totaldebs=${leftoverdebs%% *}
@@ -1004,7 +1008,7 @@ get_debs () {
 				for a in $archs; do
 					path="dists/$s/$c/binary-$a/Packages"
 					pkgdest="$TARGET/$($DLDEST pkg "$s" "$c" "$a" "$m1" "$path")"
-					echo "$("$PKGDETAILS" FIELD "$field" "$m1" "$pkgdest" "$@" | sed 's/ .*//')"
+					"$PKGDETAILS" FIELD "$field" "$m1" "$pkgdest" "$@" | sed 's/ .*//'
 				done
 			done
 		done
@@ -1118,7 +1122,7 @@ extract () { (
 	local p cat_cmd pkg
 	p=0
 	for pkg in $(debfor "$@"); do
-		p=$(($p + 1))
+		p=$((p + 1))
 		progress "$p" "$#" EXTRACTPKGS "Extracting packages"
 		packagename="$(echo "$pkg" | sed 's,^.*/,,;s,_.*$,,')"
 		info EXTRACTING "Extracting %s..." "$packagename"
@@ -1145,7 +1149,8 @@ in_target_failmsg () {
 		msg="See %s for details"
 		if [ -e "$TARGET/debootstrap/debootstrap.log" ]; then
 			arg="$TARGET/debootstrap/debootstrap.log"
-			local pkg="$(grep '^dpkg: error processing ' "$TARGET/debootstrap/debootstrap.log" | head -n 1 | sed 's/\(error processing \)\(package \|archive \)/\1/' | cut -d ' ' -f 4)"
+			local pkg
+			pkg="$(grep '^dpkg: error processing ' "$TARGET/debootstrap/debootstrap.log" | head -n 1 | sed 's/\(error processing \)\(package \|archive \)/\1/' | cut -d ' ' -f 4)"
 			if [ -n "$pkg" ]; then
 				msg="$msg (possibly the package $pkg is at fault)"
 			fi
@@ -1382,7 +1387,7 @@ setup_devices_simple () {
 }
 
 setup_devices_fakechroot () {
-	rm -rf "$TARGET/dev"
+	rm -rf "${TARGET:?}/dev"
 	ln -s /dev "$TARGET"
 }
 
@@ -1760,8 +1765,9 @@ resolve_deps () {
 		for a in $archs; do
 			for s in $SUITE $EXTRA_SUITES; do
 				for c in ${COMPONENTS:-$(echo "${USE_COMPONENTS}" | tr '|' ' ')}; do
-					local path="dists/$s/$c/binary-$a/Packages"
-					local pkgdest="$TARGET/$($DLDEST pkg "$s" "$c" "$a" "$m1" "$path")"
+					local path pkgdest
+					path="dists/$s/$c/binary-$a/Packages"
+					pkgdest="$TARGET/$($DLDEST pkg "$s" "$c" "$a" "$m1" "$path")"
 					NEWPKGS="$NEWPKGS $("$PKGDETAILS" GETDEPS "$pkgdest" $PKGS)"
 				done
 			done
@@ -1774,8 +1780,9 @@ resolve_deps () {
 		for a in $archs; do
 			for s in $SUITE $EXTRA_SUITES; do
 				for c in ${COMPONENTS:-$(echo "${USE_COMPONENTS}" | tr '|' ' ')}; do
-					local path="dists/$s/$c/binary-$a/Packages"
-					local pkgdest="$TARGET/$($DLDEST pkg "$s" "$c" "$a" "$m1" "$path")"
+					local path pkgdest
+					path="dists/$s/$c/binary-$a/Packages"
+					pkgdest="$TARGET/$($DLDEST pkg "$s" "$c" "$a" "$m1" "$path")"
 					REALPKGS="$REALPKGS $("$PKGDETAILS" PKGS REAL "$pkgdest" $PKGS | sed -n 's/ .*REAL.*$//p')"
 				done
 			done
@@ -1817,7 +1824,8 @@ setup_available () {
 }
 
 get_next_predep () {
-	local stanza="$(in_target_nofail dpkg --predep-package)"
+	local stanza
+	stanza="$(in_target_nofail dpkg --predep-package)"
 	[ "$stanza" ] || return 1
 	echo "$stanza" | grep '^Package:' | sed 's/^Package://; s/^ *//'
 }
@@ -1880,7 +1888,7 @@ EOF
 
 read_gpg_status () {
 	local badsig unkkey validsig
-	while read prefix keyword keyid rest; do
+	while read -r prefix keyword keyid rest; do
 		[ "$prefix" = '[GNUPG:]' ] || continue
 		case $keyword in
 		    BADSIG)	badsig="$keyid" ;;
@@ -1914,7 +1922,7 @@ repeatn () {
 		if "$@"; then
 			break
 		else
-			n=$(( $n - 1 ))
+			n=$(( n - 1 ))
 			sleep 1
 		fi
 	done
@@ -1926,8 +1934,8 @@ N_EXIT_THINGS=0
 exit_function () {
 	local n=0
 	while [ "$n" -lt "$N_EXIT_THINGS" ]; do
-		(eval $(eval echo \${EXIT_THING_$n}) 2>/dev/null || true)
-		n=$(( $n + 1 ))
+		(eval "$(eval "echo \${EXIT_THING_$n}")" 2>/dev/null || true)
+		n=$(( n + 1 ))
 	done
 	N_EXIT_THINGS=0
 }
@@ -1939,15 +1947,15 @@ trap "exit 131" 3
 trap "exit 143" 15
 
 on_exit () {
-	eval "$(echo EXIT_THING_${N_EXIT_THINGS}=\"$1\")"
-	N_EXIT_THINGS=$(( $N_EXIT_THINGS + 1 ))
+	eval "EXIT_THING_${N_EXIT_THINGS}=\"$1\""
+	N_EXIT_THINGS=$(( N_EXIT_THINGS + 1 ))
 }
 
 ############################################################## fakechroot tools
 
 install_fakechroot_tools () {
 	if [ "$VARIANT" = "fakechroot" ]; then
-		export PATH=/usr/sbin:/sbin:$PATH
+		export PATH="/usr/sbin:/sbin:$PATH"
 	fi
 
 	mv "$TARGET/sbin/ldconfig" "$TARGET/sbin/ldconfig.REAL"
